#
# The following environment variables are required:
#
# CUDA_INSTALL_PATH - CUDA base directory
# OPS_COMPILER      - Compiler toolchain: gnu (gcc, gfortran) or pgi (pgc++, pgfortran)
# OPS_INSTALL_PATH  - OPS base directory
#

OPS = $(OPS_INSTALL_PATH)
C_OPS = $(OPS)/c
C_OPS_INC = $(C_OPS)/include
C_OPS_SRC = $(C_OPS)/src

F_OPS = $(OPS)/fortran
F_OPS_INC = $(F_OPS)/include
F_OPS_SRC = $(F_OPS)/src
F_OPS_OBJ = $(F_OPS)/obj
F_OPS_LIB = $(F_OPS)/lib
F_OPS_MOD = $(F_OPS)/mod
