//
// auto-generated by ops.py
//
#include "./OpenMP4/clover_leaf_common.h"

#define OPS_GPU

extern int xdim0_ideal_gas_kernel;
extern int xdim1_ideal_gas_kernel;
extern int xdim2_ideal_gas_kernel;
extern int xdim3_ideal_gas_kernel;

#undef OPS_ACC0
#undef OPS_ACC1
#undef OPS_ACC2
#undef OPS_ACC3

#define OPS_ACC0(x, y) (x + xdim0_ideal_gas_kernel * (y))
#define OPS_ACC1(x, y) (x + xdim1_ideal_gas_kernel * (y))
#define OPS_ACC2(x, y) (x + xdim2_ideal_gas_kernel * (y))
#define OPS_ACC3(x, y) (x + xdim3_ideal_gas_kernel * (y))

// user function

void ideal_gas_kernel_c_wrapper(double *p_a0, int base0, int tot0, double *p_a1,
                                int base1, int tot1, double *p_a2, int base2,
                                int tot2, double *p_a3, int base3, int tot3,
                                int x_size, int y_size) {
#ifdef OPS_GPU

#pragma omp target teams distribute parallel for num_teams(OPS_threads)        \
    thread_limit(OPS_threads_for_block) schedule(static, 1)
#endif
  for (int i = 0; i < y_size * x_size; i++) {
    int n_x = i % x_size;
    int n_y = i / x_size;
    const double *density =
        p_a0 + base0 + n_x * 1 * 1 + n_y * xdim0_ideal_gas_kernel * 1 * 1;

    const double *energy =
        p_a1 + base1 + n_x * 1 * 1 + n_y * xdim1_ideal_gas_kernel * 1 * 1;
    double *pressure =
        p_a2 + base2 + n_x * 1 * 1 + n_y * xdim2_ideal_gas_kernel * 1 * 1;

    double *soundspeed =
        p_a3 + base3 + n_x * 1 * 1 + n_y * xdim3_ideal_gas_kernel * 1 * 1;

    double sound_speed_squared, v, pressurebyenergy, pressurebyvolume;

    v = 1.0 / density[OPS_ACC0(0, 0)];
    pressure[OPS_ACC2(0, 0)] =
        (1.4 - 1.0) * density[OPS_ACC0(0, 0)] * energy[OPS_ACC1(0, 0)];
    pressurebyenergy = (1.4 - 1.0) * density[OPS_ACC0(0, 0)];
    pressurebyvolume = -1 * density[OPS_ACC0(0, 0)] * pressure[OPS_ACC2(0, 0)];
    sound_speed_squared = v * v * (pressure[OPS_ACC2(0, 0)] * pressurebyenergy -
                                   pressurebyvolume);
    soundspeed[OPS_ACC3(0, 0)] = sqrt(sound_speed_squared);
  }
}
#undef OPS_ACC0
#undef OPS_ACC1
#undef OPS_ACC2
#undef OPS_ACC3
