//
// auto-generated by ops.py
//
#include "./OpenMP4/clover_leaf_common.h"

#define OPS_GPU

extern int xdim0_initialise_chunk_kernel_x;
extern int xdim1_initialise_chunk_kernel_x;
extern int xdim2_initialise_chunk_kernel_x;

#undef OPS_ACC0
#undef OPS_ACC1
#undef OPS_ACC2

#define OPS_ACC0(x, y) (x + xdim0_initialise_chunk_kernel_x * (y))
#define OPS_ACC1(x, y) (x + xdim1_initialise_chunk_kernel_x * (y))
#define OPS_ACC2(x, y) (x + xdim2_initialise_chunk_kernel_x * (y))

// user function

void initialise_chunk_kernel_x_c_wrapper(double *p_a0, int base0, int tot0,
                                         int *p_a1, int base1, int tot1,
                                         double *p_a2, int base2, int tot2,
                                         int x_size, int y_size) {
  int num_blocks = OPS_threads;
#pragma omp target enter data map(                                             \
    to : p_a0[0 : tot0], p_a1[0 : tot1], p_a2[0 : tot2],                       \
                                              states[0 : number_of_states])
#ifdef OPS_GPU

#pragma omp target teams num_teams(num_blocks)                                 \
    thread_limit(OPS_threads_for_block)
#pragma omp distribute parallel for simd schedule(static, 1)
#endif
  for (int i = 0; i < y_size * x_size; i++) {
#ifdef OPS_GPU
#endif
    int n_x = i % x_size;
    int n_y = i / x_size;
    double *vertexx = p_a0 + base0 + n_x * 1 * 1 +
                      n_y * xdim0_initialise_chunk_kernel_x * 0 * 1;

    const int *xx = p_a1 + base1 + n_x * 1 * 1 +
                    n_y * xdim1_initialise_chunk_kernel_x * 0 * 1;
    double *vertexdx = p_a2 + base2 + n_x * 1 * 1 +
                       n_y * xdim2_initialise_chunk_kernel_x * 0 * 1;

    int x_min = field.x_min - 2;
    double min_x, d_x;

    d_x = (grid.xmax - grid.xmin) / (double)grid.x_cells;
    min_x = grid.xmin + d_x * field.left;

    vertexx[OPS_ACC0(0, 0)] = min_x + d_x * (xx[OPS_ACC1(0, 0)] - x_min);
    vertexdx[OPS_ACC2(0, 0)] = (double)d_x;
  }
}
#undef OPS_ACC0
#undef OPS_ACC1
#undef OPS_ACC2
