# File: .readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: doc/requirement.txt

formats:
- epub
- pdf
