//
// auto-generated by ops.py
//

int xdim0_initialise_chunk_kernel_celly;
int xdim1_initialise_chunk_kernel_celly;
int xdim2_initialise_chunk_kernel_celly;


#define OPS_ACC0(x,y) (n_x*0 + x + (n_y*1+(y))*xdim0_initialise_chunk_kernel_celly)
#define OPS_ACC1(x,y) (n_x*0 + x + (n_y*1+(y))*xdim1_initialise_chunk_kernel_celly)
#define OPS_ACC2(x,y) (n_x*0 + x + (n_y*1+(y))*xdim2_initialise_chunk_kernel_celly)
//user function



void initialise_chunk_kernel_celly_c_wrapper(
  const double * restrict vertexy,
  double * restrict celly,
  double * restrict celldy,
  int x_size, int y_size) {
  #pragma omp parallel for
  for ( int n_y=0; n_y<y_size; n_y++ ){
    for ( int n_x=0; n_x<x_size; n_x++ ){
      

  double d_y;
  d_y = (grid.ymax - grid.ymin)/(double)grid.y_cells;

  celly(0,0) = 0.5*( vertexy(0,0)+ vertexy(0,1) );
  celldy(0,0) = d_y;



    }
  }
}
#undef OPS_ACC0
#undef OPS_ACC1
#undef OPS_ACC2

