//
// auto-generated by op2.py on 2013-11-05 14:40
//

//header
#include "ops_lib_cpp.h"

//user kernel files
#include "accelerate_kernel_stepbymass_omp_kernel.cpp"
#include "accelerate_kernelx1_omp_kernel.cpp"
#include "accelerate_kernely1_omp_kernel.cpp"
#include "accelerate_kernelx2_omp_kernel.cpp"
#include "accelerate_kernely2_omp_kernel.cpp"
