macro(TEST CMD ARG OPS_INSTALL_PATH)
    set(ENV{OPS_INSTALL_PATH} ${OPS_INSTALL_PATH})
    separate_arguments(args NATIVE_COMMAND  ${ARG})
    execute_process(COMMAND ${CMD} ${args} OUTPUT_FILE perf.out)
    execute_process(COMMAND grep "PASSED" perf.out RESULT_VARIABLE RES)
    # message("RES=${RES}")
    if(RES)
        message(FATAL_ERROR "Error running ${CMD}")
    endif()
endmacro()
TEST(${CMD} ${ARG} ${OPS_INSTALL_PATH})