if(OPS_FORTRAN)
  find_package(MPI QUIET COMPONENTS CXX Fortran)
  message(STATUS "MPICXX FOUND ${MPI_CXX_FOUND}")
  message(STATUS "MPIF90 FOUND ${MPI_Fortran_FOUND}")
else(OPS_FORTRAN)
  find_package(MPI QUIET COMPONENTS CXX)
  message(STATUS "MPICXX FOUND ${MPI_CXX_FOUND}")
endif()
if(NOT MPI_FOUND)
  message(WARNING "MPI environment NOT FOUND! Only sequential code will be compiled!")
endif()
