//
// auto-generated by ops.py
//
//header
#include <math.h>
#define OPS_API 2
#define OPS_3D
#define OPS_SOA
#include "ops_macros.h"
#ifdef __cplusplus
#include "ops_lib_core.h"
#endif
#if defined(OPS_MPI) && defined(__cplusplus)
#include "ops_mpi_core.h"
#endif

// global constants
