# Flags for MS compiler
# C
set(OPS_CFLAGS "-W1")
set(OPS_CFLAGS_RELEASE "/O2 /Ot")
set(OPS_CFLAGS_DEBUG   "/Z7 /DEBUG")
# CXX
set(OPS_CXXFLAGS "-W1")
set(OPS_CXXFLAGS_RELEASE "/O2 /Ot")
set(OPS_CXXFLAGS_DEBUG   "/Z7 /DEBUG")
