//
// auto-generated by ops.py
//

#include "./MPI_inline/shsgc_common.h"
//user kernel files
#include "gridgen_kernel_mpiinline_kernel_c.c"
#include "init_kernel_mpiinline_kernel_c.c"
#include "save_kernel_mpiinline_kernel_c.c"
#include "calvar_kernel_mpiinline_kernel_c.c"
#include "xder1_kernel_mpiinline_kernel_c.c"
#include "residue_eval_mpiinline_kernel_c.c"
#include "updateRK3_kernel_mpiinline_kernel_c.c"
#include "Riemann_kernel_mpiinline_kernel_c.c"
#include "limiter_kernel_mpiinline_kernel_c.c"
#include "tvd_kernel_mpiinline_kernel_c.c"
#include "vars_kernel_mpiinline_kernel_c.c"
#include "calupwindeff_kernel_mpiinline_kernel_c.c"
#include "fact_kernel_mpiinline_kernel_c.c"
#include "update_kernel_mpiinline_kernel_c.c"
#include "checkop_kernel_mpiinline_kernel_c.c"
