
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.common
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.mpi
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.cuda
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.hdf5

OPS_FILES=laplace2d.F90

OPS_GENERATED=laplace2d_ops.F90

OTHER_FILES=constants.F90

APP = laplace
MAIN_SRC=laplace2d

include $(OPS_INSTALL_PATH)/../makefiles/Makefile.f_app
