//
// auto-generated by ops.py on 2014-07-31 12:19
//

#include "./OpenACC/clover_leaf_common.h"

#define OPS_GPU

int xdim0_flux_calc_kernely;
int ydim0_flux_calc_kernely;
int xdim1_flux_calc_kernely;
int ydim1_flux_calc_kernely;
int xdim2_flux_calc_kernely;
int ydim2_flux_calc_kernely;
int xdim3_flux_calc_kernely;
int ydim3_flux_calc_kernely;

#define OPS_ACC0(x,y,z) (x+xdim0_flux_calc_kernely*(y)+xdim0_flux_calc_kernely*ydim0_flux_calc_kernely*(z))
#define OPS_ACC1(x,y,z) (x+xdim1_flux_calc_kernely*(y)+xdim1_flux_calc_kernely*ydim1_flux_calc_kernely*(z))
#define OPS_ACC2(x,y,z) (x+xdim2_flux_calc_kernely*(y)+xdim2_flux_calc_kernely*ydim2_flux_calc_kernely*(z))
#define OPS_ACC3(x,y,z) (x+xdim3_flux_calc_kernely*(y)+xdim3_flux_calc_kernely*ydim3_flux_calc_kernely*(z))

//user function
inline 
void flux_calc_kernely( double *vol_flux_y, const double *yarea,
                        const double *yvel0, const double *yvel1) {

  vol_flux_y[OPS_ACC0(0,0,0)] = 0.125 * dt * (yarea[OPS_ACC1(0,0,0)]) *
  ( yvel0[OPS_ACC2(0,0,0)] + yvel0[OPS_ACC2(1,0,0)] + yvel0[OPS_ACC2(0,0,1)] + yvel0[OPS_ACC2(1,0,1)] +
    yvel1[OPS_ACC3(0,0,0)] + yvel1[OPS_ACC3(1,0,0)] + yvel1[OPS_ACC3(0,0,1)] + yvel1[OPS_ACC3(1,0,1)]);
}



#undef OPS_ACC0
#undef OPS_ACC1
#undef OPS_ACC2
#undef OPS_ACC3


void flux_calc_kernely_c_wrapper(
  double *p_a0,
  double *p_a1,
  double *p_a2,
  double *p_a3,
  int x_size, int y_size, int z_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1,p_a2,p_a3)
  #pragma acc loop
  #endif
  for ( int n_z=0; n_z<z_size; n_z++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_y=0; n_y<y_size; n_y++ ){
      #ifdef OPS_GPU
      #pragma acc loop
      #endif
      for ( int n_x=0; n_x<x_size; n_x++ ){
        flux_calc_kernely(  p_a0 + n_x*1 + n_y*xdim0_flux_calc_kernely*1 + n_z*xdim0_flux_calc_kernely*ydim0_flux_calc_kernely*1,
           p_a1 + n_x*1 + n_y*xdim1_flux_calc_kernely*1 + n_z*xdim1_flux_calc_kernely*ydim1_flux_calc_kernely*1,
           p_a2 + n_x*1 + n_y*xdim2_flux_calc_kernely*1 + n_z*xdim2_flux_calc_kernely*ydim2_flux_calc_kernely*1,
           p_a3 + n_x*1 + n_y*xdim3_flux_calc_kernely*1 + n_z*xdim3_flux_calc_kernely*ydim3_flux_calc_kernely*1 );

      }
    }
  }
}
