//
// auto-generated by ops.py
//
#include "./OpenACC/multidim_common.h"

#define OPS_GPU

int xdim0_multidim_reduce_kernel;


#define OPS_ACC_MD0(d,x,y) ((x)*2+(d)+(xdim0_multidim_reduce_kernel*(y)*2))
//user function
inline
void multidim_reduce_kernel(const double *val, double *redu_dat1) {

  redu_dat1[0] = redu_dat1[0] + val[OPS_ACC_MD0(0,0,0)];
  redu_dat1[1] = redu_dat1[1] + val[OPS_ACC_MD0(1,0,0)];
}



#undef OPS_ACC_MD0


void multidim_reduce_kernel_c_wrapper(
  double *p_a0,
  double *p_a1,
  int x_size, int y_size) {
  double p_a1_l[2];
  for (int d = 0; d < 2; d++) p_a1_l[d] = p_a1[d];
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0) reduction(+:p_a1_l)
  #pragma acc loop reduction(+:p_a1_l)
  #endif
  for ( int n_y=0; n_y<y_size; n_y++ ){
    #ifdef OPS_GPU
    #pragma acc loop reduction(+:p_a1_l)
    #endif
    for ( int n_x=0; n_x<x_size; n_x++ ){
      multidim_reduce_kernel(  p_a0 + n_x*1*2 + n_y*xdim0_multidim_reduce_kernel*1*2,
           p_a1_l );

    }
  }
  for (int d = 0; d < 2; d++) p_a1[d] = p_a1_l[d];
}
