set(ENV{OPS_INSTALL_PATH} ${OPS_INSTALL_PATH})
execute_process(COMMAND ${WRITE_SEQ} OUTPUT_FILE perf.out RESULT_VARIABLE RES)
if(RES)
    message(FATAL_ERROR "Error running write_seq")
endif()
file(RENAME write_data.h5 write_data_seq.h5)
separate_arguments(WRITE_ARG NATIVE_COMMAND  ${W_ARG})
execute_process(COMMAND ${WRITE} ${WRITE_ARG} OUTPUT_FILE perf.out RESULT_VARIABLE RES)
if(RES)
    message(FATAL_ERROR "Error running ${WRITE}")
endif()
separate_arguments(READ_ARG NATIVE_COMMAND  ${R_ARG})
execute_process(COMMAND ${READ} ${READ_ARG} OUTPUT_FILE perf.out RESULT_VARIABLE RES)
if(RES)
    message(FATAL_ERROR "Error running ${READ}")
endif()
execute_process(COMMAND "${H5D}" write_data.h5 read_data.h5 OUTPUT_FILE diff.out RESULT_VARIABLE RES)
if(RES)
    message(FATAL_ERROR "h5diff fails")
endif()
execute_process(COMMAND "${H5D}" write_data_seq.h5 read_data.h5 OUTPUT_FILE diff.out RESULT_VARIABLE RES)
if(RES)
    message(FATAL_ERROR "h5diff fails when comparing with sequential data")
endif()
FILE(REMOVE write_data.h5 read_data.h5 write_data_seq.h5)
