#!/bin/bash
#A rough example of environmental variables for compiling with Intel compilers
#unset and set defaults

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
unset LD_LIBRARY_PATH
module purge
. ~/.bashrc
#. /opt/modules/current/Modules/3.2.6/init/bash
#module load gnu-5.4.0
export PATH=/rr-home/gihan/numawrap:$PATH

#OPS specifics
export OPS_COMPILER=intel
export OPS_INSTALL_PATH=/rr-home/gihan/OPS/ops

#CUDA and NVIDIA OpenCL
export NV_ARCH=Pascal
module load cuda/toolkit-9.1.85
export CUDA_INSTALL_PATH=/opt/cuda/9.1.85/toolkit/
export OPENCL_INSTALL_PATH=/opt/cuda/9.1.85/toolkit/
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/opencl/intel-2013b/lib64/

#Intel MPI and Compilers
source /opt/intel/parallelstudio/2017/update2/x86_64/parallel_studio_xe_2017.2.050/psxevars.sh
export MPICPP=mpicxx
export PATH=$PATH:/opt/intel/parallelstudio/2017/update2/x86_64/bin
export MPI_INSTALL_PATH=/opt/intel/parallelstudio/2017/update2/x86_64/impi/2017.2.174/intel64/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/intel/parallelstudio/2017/update2/x86_64/impi/2017.2.174/intel64/lib/

export MPICH_CXX=/opt/intel/parallelstudio/2017/update2/x86_64/bin/icpc
export MPICH_CC=/opt/intel/parallelstudio/2017/update2/x86_64/bin/icc
export MPICH_F90=/opt/intel/parallelstudio/2017/update2/x86_64/bin/ifort

#HDF5
export HDF5_INSTALL_PATH=/opt/hdf5/1.8.18/intel/15.0u6/impi/5.0u3/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/hdf5/1.8.18/intel/15.0u6/impi/5.0u3/lib/

#Tridiagonal LIB
export TRID_INSTALL_PATH=/rr-home/gihan/tridsolver/scalar/build/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/tridsolver/scalar/build/lib/

