#!/bin/bash
#A rough example of environmental variables for compiling with PGI/NVHPC compilers

#unset and set defaults
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
unset LD_LIBRARY_PATH
module purge
. ~/.bashrc
export PATH=/rr-home/gihan/numawrap:$PATH
module load cmake/3.20.1

#OPS specifics
export OPS_COMPILER=pgi
export OPS_INSTALL_PATH=/rr-home/gihan/OPS/ops
export OP_AUTO_SOA=1

#module load llvm-14.0.6/llvm-14.0.6
#export LIBCLANG_PATH=/opt/llvm/14.0.6/lib/libclang.so

module load python/3.9.7

#Uncomment the following to test/reinstall the environment setup for the code-gen
#cd  $OPS_INSTALL_PATH/../ops_translator/
#rm -rf ./ops_venv
#. setup_venv.sh
#cd -
module load python/3.9.7
source $OPS_INSTALL_PATH/../ops_translator/ops_venv/bin/activate

#PGI/NVIDIA MPI and Compilers
module load nvhpc/24.3
export MPI_INSTALL_PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/24.3/comm_libs/12.3/openmpi4/openmpi-4.1.5/
export PATH=$MPI_INSTALL_PATH/bin:$PATH
export LD_LIBRARY_PATH=$MPI_INSTALL_PATH/lib:$LD_LIBRARY_PATH


export MPICC=mpicc
export MPICPP=mpic++
export MPICXX=mpicxx
export MPIFC=mpif90
export MPIF90=mpif90
export MPIF90_F90=pgfortran
export MPICH_FC=pgfortran

echo "MPICC=$MPICC"
echo "MPICPP=$MPICPP"
echo "MPICXX=$MPICXX"

#CUDA and NVIDIA OpenCL
if (lspci | grep -i 'nvidia') then

export NV_ARCH=Hopper
echo "GPU architecture" $NV_ARCH

unset SYCL_INSTALL_PATH

export CUDA_INSTALL_PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/24.3/cuda/
export CUDA_MATH_LIBS=$CUDA_INSTALL_PATH/../math_libs/lib64

export LD_LIBRARY_PATH=$CUDA_INSTALL_PATH/lib64:$LD_LIBRARY_PATH
else
unset CUDA_INSTALL_PATH
fi

#PGI based HDF5
unset HDF5_INSTALL_PATH
#export HDF5_INSTALL_PATH=/rr-home/gihan/HDF5-PGI-18
#export LD_LIBRARY_PATH=/rr-home/gihan/HDF5-PGI-18/lib:$LD_LIBRARY_PATH
export HDF5_INSTALL_PATH=/rr-home/gihan//HDF5/build_hdf5/gnu/
export LD_LIBRARY_PATH=/rr-home/gihan//HDF5/build_hdf5/gnu/lib:$LD_LIBRARY_PATH
#export HDF5_INSTALL_PATH=/ext-home/asl/install/build_hdf5/gnu
#export PATH=$HDF5_INSTALL_PATH/bin:$PATH
export LD_LIBRARY_PATH=$HDF5_INSTALL_PATH/lib:$LD_LIBRARY_PATH

#Tridiagonal LIB
export TDMA_INSTALL_PATH=~/tridsolver/scalar/libtrid
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TDMA_INSTALL_PATH/lib/
#unset TDMA_INSTALL_PATH 
#unset LD_LIBRARY_PATH

#OpenSBLI -- for testing app TGV only
export OPENSBLI_INSTALL_PATH=/rr-home/gihan/OpenSBLI/OpenSBLI_OPS_TESTING/opensbli/

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/rr-home/gihan/libffi/

