include $(OPS_INSTALL_PATH)/../makefiles/Makefile.common
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.mpi
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.cuda
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.hdf5

OPS_FILES=tilingcheck.F90

OPS_GENERATED=

OTHER_FILES=constants.F90

APP = tilingcheck
MAIN_SRC=tilingcheck

include $(OPS_INSTALL_PATH)/../makefiles/Makefile.f_app
