include $(OPS_INSTALL_PATH)/../makefiles/Makefile.common
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.mpi
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.cuda
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.hdf5

OTHER_FILES=constants.F90
OPS_FILES=multidim.F90
OPS_GENERATED=multidim_ops.F90

APP = multidim
MAIN_SRC=multidim
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.f_app
