//
// auto-generated by ops.py
//
#include "./OpenMP4/clover_leaf_common.h"
#include <omp.h>
#define OPS_GPU

extern int xdim0_calc_dt_kernel_min;
extern int ydim0_calc_dt_kernel_min;

#undef OPS_ACC0

#define OPS_ACC0(x, y, z)                                                      \
  (n_x * 1 * 1 + n_y * xdim0_calc_dt_kernel_min * 1 * 1 +                      \
   n_z * xdim0_calc_dt_kernel_min * ydim0_calc_dt_kernel_min * 1 + x +         \
   xdim0_calc_dt_kernel_min * (y) +                                            \
   xdim0_calc_dt_kernel_min * ydim0_calc_dt_kernel_min * (z))

// user function

void calc_dt_kernel_min_c_wrapper(double *p_a0, double *p_a1, int x_size,
                                  int y_size, int z_size) {
  double p_a1_0 = p_a1[0];
#ifdef OPS_GPU

#pragma omp target teams distribute parallel for map(tofrom : p_a1_0)          \
    reduction(min : p_a1_0)
#endif
  for (int i = 0; i < y_size * x_size * z_size; i++) {
    const int id =
        omp_get_num_threads() * omp_get_team_num() + omp_get_thread_num();
    const int n_x = id % x_size;
    const int n_y = (id / x_size) % y_size;
    const int n_z = id / (x_size * y_size);
    const double *dt_min = p_a0;

    double *dt_min_val = &p_a1_0;

    *dt_min_val = MIN(*dt_min_val, dt_min[OPS_ACC0(0, 0, 0)]);
  }
  p_a1[0] = p_a1_0;
}
#undef OPS_ACC0
