//
// auto-generated by ops.py
//
#include "./OpenMP4/clover_leaf_common.h"
#include <omp.h>
#define OPS_GPU

extern int xdim0_initialise_chunk_kernel_yy;
extern int ydim0_initialise_chunk_kernel_yy;

#undef OPS_ACC0

#define OPS_ACC0(x, y, z)                                                      \
  (n_x * 0 * 1 + n_y * xdim0_initialise_chunk_kernel_yy * 1 * 1 +              \
   n_z * xdim0_initialise_chunk_kernel_yy * ydim0_initialise_chunk_kernel_yy * \
       0 +                                                                     \
   x + xdim0_initialise_chunk_kernel_yy * (y) +                                \
   xdim0_initialise_chunk_kernel_yy * ydim0_initialise_chunk_kernel_yy * (z))

// user function

void initialise_chunk_kernel_yy_c_wrapper(int *p_a0, int *p_a1, int arg_idx0,
                                          int arg_idx1, int arg_idx2,
                                          int x_size, int y_size, int z_size) {
#ifdef OPS_GPU

#pragma omp target teams distribute parallel for
#endif
  for (int i = 0; i < y_size * x_size * z_size; i++) {
    const int id =
        omp_get_num_threads() * omp_get_team_num() + omp_get_thread_num();
    const int n_x = id % x_size;
    const int n_y = (id / x_size) % y_size;
    const int n_z = id / (x_size * y_size);
    int arg_idx[] = {arg_idx0 + n_x, arg_idx1 + n_y, arg_idx2 + n_z};
    int *yy = p_a0;

    int *idx = arg_idx;

    yy[OPS_ACC0(0, 0, 0)] = idx[1] - 2;
  }
}
#undef OPS_ACC0
