//
// auto-generated by ops.py
//
#include "./OpenMP4/clover_leaf_common.h"

#define OPS_GPU

extern int xdim0_initialise_chunk_kernel_z;
extern int ydim0_initialise_chunk_kernel_z;
extern int xdim1_initialise_chunk_kernel_z;
extern int ydim1_initialise_chunk_kernel_z;
extern int xdim2_initialise_chunk_kernel_z;
extern int ydim2_initialise_chunk_kernel_z;

#undef OPS_OPENMP40
#undef OPS_OPENMP41
#undef OPS_OPENMP42

#define OPS_OPENMP40(x, y, z)                                                  \
  (x + xdim0_initialise_chunk_kernel_z * (y) +                                 \
   xdim0_initialise_chunk_kernel_z * ydim0_initialise_chunk_kernel_z * (z))
#define OPS_OPENMP41(x, y, z)                                                  \
  (x + xdim1_initialise_chunk_kernel_z * (y) +                                 \
   xdim1_initialise_chunk_kernel_z * ydim1_initialise_chunk_kernel_z * (z))
#define OPS_OPENMP42(x, y, z)                                                  \
  (x + xdim2_initialise_chunk_kernel_z * (y) +                                 \
   xdim2_initialise_chunk_kernel_z * ydim2_initialise_chunk_kernel_z * (z))

// user function

void initialise_chunk_kernel_z_c_wrapper(double *p_a0, int base0, int tot0,
                                         int *p_a1, int base1, int tot1,
                                         double *p_a2, int base2, int tot2,
                                         int x_size, int y_size, int z_size) {
  int num_blocks = round(((double)x_size * (double)y_size) / 128);
#pragma omp target enter data map(to : p_a0[0 : tot0], p_a1[0 : tot1],         \
                                                            p_a2[0 : tot2])
#ifdef OPS_GPU

#pragma omp target map(to : p_a0[0 : tot0], p_a1[0 : tot1], p_a2[0 : tot2])
#pragma omp teams num_teams(num_blocks) thread_limit(128)
#pragma omp distribute parallel for simd collapse(3) schedule(static, 1)
#endif
  for (int n_z = 0; n_z < z_size; n_z++) {
#ifdef OPS_GPU
#endif
    for (int n_y = 0; n_y < y_size; n_y++) {
#ifdef OPS_GPU
#endif
      for (int n_x = 0; n_x < x_size; n_x++) {
        double *vertexz = p_a0 + base0 + n_x * 0 * 1 +
                          n_y * xdim0_initialise_chunk_kernel_z * 0 * 1 +
                          n_z * xdim0_initialise_chunk_kernel_z *
                              ydim0_initialise_chunk_kernel_z * 1;

        const int *zz = p_a1 + base1 + n_x * 0 * 1 +
                        n_y * xdim1_initialise_chunk_kernel_z * 0 * 1 +
                        n_z * xdim1_initialise_chunk_kernel_z *
                            ydim1_initialise_chunk_kernel_z * 1;

        double *vertexdz = p_a2 + base2 + n_x * 0 * 1 +
                           n_y * xdim2_initialise_chunk_kernel_z * 0 * 1 +
                           n_z * xdim2_initialise_chunk_kernel_z *
                               ydim2_initialise_chunk_kernel_z * 1;

        int z_min = field.z_min - 2;

        double min_z, d_z;
        d_z = (grid.zmax - grid.zmin) / (double)grid.z_cells;
        min_z = grid.zmin + d_z * field.back;

        vertexz[OPS_ACC0(0, 0, 0)] =
            min_z + d_z * (zz[OPS_ACC1(0, 0, 0)] - z_min);
        vertexdz[OPS_ACC2(0, 0, 0)] = (double)d_z;
      }
    }
  }
}
#undef OPS_OPENMP40
#undef OPS_OPENMP41
#undef OPS_OPENMP42
