//
// auto-generated by ops.py
//

#include "./MPI_inline/lowdim_common.h"


void ops_init_backend() {}

void ops_decl_const_char2(int dim, char const *type,
int size, char *dat, char const *name){
  {
    throw OPSException(OPS_RUNTIME_ERROR, "error: unknown const name");
  }
}

//user kernel files
#include "set_val_mpiinline_kernel.cpp"
#include "calc_mpiinline_kernel.cpp"
