//
// auto-generated by ops.py
//

int xdim0_set_val;
int ydim0_set_val;


//user function



void set_val_c_wrapper(
  double * restrict dat_p,
  const double * restrict val,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        ptr_double dat = { dat_p + n_x*1 + n_y * xdim0_set_val*1 + n_z * xdim0_set_val * ydim0_set_val*1, xdim0_set_val, ydim0_set_val};
        

    OPS_ACC(dat, 0,0,0) = *val;

      }
    }
  }
}
