CC      := clang
CXX     := clang++
ifdef DEBUG
	CCFLAGS   := -O0 -std=c99 -fPIC -DUNIX -Wall -g #-ffloat-store
	CXXFLAGS   := -O0 -fPIC -DUNIX -Wall -g -std=c++11 #-ffloat-store
else
	CCFLAGS   := -O3 -std=c99 -fPIC -DUNIX -Wall -g #-ffloat-store
	CXXFLAGS  := -O3 -fPIC -DUNIX -Wall -g -std=c++11
endif
OMPFLAGS=-fopenmp
OMPOFFLOADFLAGS=-fopenmp -fopenmp-targets=nvptx64-nvidia-cuda -Xopenmp-target -march=sm_75
ifdef THREADED
	THREADING_FLAGS ?= -fopenmp
endif
