CC    := pgcc -c99
CXX     := pgc++
FC	:= pgfortran
ifdef DEBUG
	CCFLAGS   := -O0 -g
else
	CCFLAGS   := -O2 -fastsse -gopt -Mipa=fast #-Mlist #-mp=nonuma -Kieee
endif
CUDA_ALIGNE_FLAG := -D__x86_64 -D__align__\(n\)=__attribute__\(\(aligned\(n\)\)\) -D__location__\(a\)=__annotate__\(a\) -DCUDARTAPI=
CXXFLAGS  := $(CCFLAGS)
OPENACCFLAGS = $(CCFLAGS) -module $(F_INC_MOD)/openacc
FFLAGS = $(CCFLAGS) -module $(F_INC_MOD)
