ifdef HDF5_INSTALL_PATH
ifdef CHECKPOINTING
  HDF5_INC              := -I$(HDF5_INSTALL_PATH)/include
  HDF5_LIB              := -L$(HDF5_INSTALL_PATH)/lib -lhdf5_hl -lhdf5 -lz
	HDF5_LIB_SEQ          := -lops_hdf5_seq $(HDF5_LIB) 
	HDF5_LIB_MPI          := -lops_hdf5_mpi $(HDF5_LIB) 
  HDF5_INC              := $(HDF5_INC) -DCHECKPOINTING
  F_HDF5_LIB_SEQ        :=  -lops_hdf5 $(HDF5_LIB)
  F_HDF5_LIB_MPI        := $(HDF5_LIB)
endif
ifdef USE_HDF5
  HDF5_INC              := -I$(HDF5_INSTALL_PATH)/include
  HDF5_LIB              := -L$(HDF5_INSTALL_PATH)/lib -lhdf5_hl -lhdf5 -lz
	HDF5_LIB_SEQ          := -lops_hdf5_seq $(HDF5_LIB) 
	HDF5_LIB_MPI          := -lops_hdf5_mpi $(HDF5_LIB) 
  F_HDF5_LIB_SEQ        := -lops_hdf5 $(HDF5_LIB)
  F_HDF5_LIB_MPI        := $(HDF5_LIB)
endif
endif
