CC        := cc
CUDA_ALIGNE_FLAG := -D__x86_64 -D__align__\(n\)=__attribute__\(\(aligned\(n\)\)\) -D__location__\(a\)=__annotate__\(a\) -DCUDARTAPI=
CCFLAGS   := -O3 -hgnu
CXX       := CC
CXXFLAGS  := $(CCFLAGS)
