CC      := clang
CXX     := clang++
FC      := flang 
ifdef DEBUG
	CCFLAGS   := -O0 -g -Wall -fPIC  
	CXXFLAGS   := -O0 -g -Wall -fPIC 
     
else
	CCFLAGS   := -Ofast -march=native -flto -g -Wall -fPIC -fopenmp
	CXXFLAGS  := -Ofast -march=native -flto -g -Wall -fPIC -fopenmp
endif
CXXLINK := -lstdc++
FFLAGS := -Ofast -march=native -flto -g -Wall -ffree-form -ffree-line-length-none -fopenmp
FMODS  := -J$(F_INC_MOD)

OMPFLAGS=-fopenmp
ifdef THREADED
	THREADING_FLAGS ?= -fopenmp
endif
