if(OPS_FORTRAN)
  include(CheckLanguage)
  check_language(Fortran)
  if(CMAKE_Fortran_COMPILER)
    enable_language(Fortran)
  else()
    message(WARNING "No Fortran support: fortran build is now deactivated")
    set(OPS_FORTRAN OFF CACHE BOOL "Turn on the Fortran build" FORCE)
  endif()
endif()
