include $(OPS_INSTALL_PATH)/../makefiles/Makefile.common
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.mpi
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.cuda
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.hdf5

OTHER_FILES=constants.F90
OPS_FILES=mblock.F90
OPS_GENERATED=mblock_ops.F90

APP = mblock
MAIN_SRC=mblock
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.f_app
