
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.common
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.mpi
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.pgi
USE_HDF5=1
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.hdf5


OTHER_FILES=constants.F90

OPS_FILES=mathtest.F90

OPS_GENERATED=mathtest_ops.F90

APP=mathtest
MAIN_SRC=mathtest

include $(OPS_INSTALL_PATH)/../makefiles/Makefile.f_app
